kind: pipeline
name: linux-amd64

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

steps:
- name: stolon-pg12
  image: plugins/docker
  settings:
    dockerfile: examples/kubernetes/image/docker/Dockerfile
    context: .
    registry: quay.io
    repo: quay.io/josua-sr/stolon-amd64
    build_args:
    - PGVERSION=12
    purge: false
    force_tag: true
    tags:
    - latest-pg12
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password

---
kind: pipeline
name: linux-arm64

clone:
  depth: 1

platform:
  os: linux
  arch: arm64

steps:
- name: stolon-pg12
  image: plugins/docker
  settings:
    dockerfile: examples/kubernetes/image/docker/Dockerfile
    context: .
    registry: quay.io
    repo: quay.io/josua-sr/stolon-arm64
    build_args:
    - PGVERSION=12
    purge: false
    force_tag: true
    tags:
    - latest-pg12
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password

---
kind: pipeline
name: manifest

clone:
  disable: true

platform:
  os: linux

steps:
- name: stolon-pg12
  image: plugins/manifest
  settings:
    target: quay.io/josua-sr/stolon:latest-pg12
    template: quay.io/josua-sr/stolon-ARCH:latest-pg12
    tags:
    - latest-pg12
    platforms:
    - linux/amd64
    - linux/arm64
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password

depends_on:
- linux-amd64
- linux-arm64
